FROM ghcr.io/siderolabs/talosctl:v1.14.1@sha256:30791b2ec3ab1dec4093c342306159ebfe876eb9f646d5a710b853844a65ba13 AS talosctl

FROM registry.fedoraproject.org/fedora-toolbox:43@sha256:01653304dfc3e9e11e7eb35e6a3b672fa2a1c077d7ab5d0028601e3dab1e50c0

COPY --from=talosctl /talosctl /usr/local/bin/talosctl

ADD kubernetes.repo /etc/yum.repos.d/

RUN dnf -y install kubectl helm libvirt-client; dnf clean all

