FROM registry.fedoraproject.org/fedora-toolbox:44@sha256:e8cf353ec9b124dbc7cc162a8fd5e87e30b96bc91a219b06f22314c61708a04f

COPY toolbox-packages /root/

RUN dnf update -y; dnf install -y $(</root/toolbox-packages); dnf clean all
