FROM registry.fedoraproject.org/fedora-toolbox:44@sha256:32fc665c4df3a7a462c5116eeccf8b22843e554fa089938ba3b4eee045616252

COPY toolbox-packages /root/

RUN dnf update -y; dnf install -y $(</root/toolbox-packages); dnf clean all
