FROM registry.fedoraproject.org/fedora-toolbox:44@sha256:9e0cd6ee0d348612757abfee3f3b7986bc23290523f13986a6d3279529bf76cb

COPY toolbox-packages /root/

RUN dnf update -y; dnf install -y $(</root/toolbox-packages); dnf clean all
