name: Build Ansible Toolbox image

on:
  push:
    branches:
      - main
    paths:
       - ansible-toolbox/**
       - .github/workflows/ansible-toolbox-build.yaml
  
  workflow_dispatch:
         

env:
  repostitory: quay.io/caracan
  context: ansible-toolbox
  image_name: ansible-toolbox
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v6

      - name: Get Versions for Tags 
        id: version_tags
        run: |
          VERSION=$(jq -r '.major + "." + .minor + "." + .zstream' ${context}/version.json)
          MAJOR=$(jq -r '.major' ${context}/version.json)
          MINOR=$(jq -r '.minor' ${context}/version.json)
          TAGS=latest
          
          TAGS+=" ${VERSION} ${MAJOR} ${MAJOR}.${MINOR}"
          echo "IMAGE_TAGS=$TAGS" >> $GITHUB_OUTPUT
          echo "CONTAINER_VERSON=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up qemu
        uses:  docker/setup-qemu-action@v4

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          context: ${{ env.context }}
          image: ${{ env.image_name }}
          tags: ${{ steps.version_tags.outputs.IMAGE_TAGS }}
          containerfiles: |
            ./${{  env.context }}/Containerfile
          platforms: linux/amd64
      
      - name: Build and publish image to Quay
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-image.outputs.image }}
          tags: ${{ steps.build-image.outputs.tags }}
          registry: ${{ env.repostitory }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
          
    env:
      BUILDAH_FORMAT: docker
      BUILDAH_ISOLATION: chroot
